import type { MessageKey } from "../locales/uk";
import { ApiError } from "./api";
import type { Translator } from "./i18n";

const apiErrorKeys: Record<string, MessageKey> = {
  ACCESS_REVOKED: "errors.ACCESS_REVOKED",
  ADMIN_EDIT_REASON_REQUIRED: "errors.ADMIN_EDIT_REASON_REQUIRED",
  ADMIN_REQUIRED: "errors.ADMIN_REQUIRED",
  APPROVAL_REQUIRED: "errors.APPROVAL_REQUIRED",
  AVATAR_REQUIRED: "errors.AVATAR_REQUIRED",
  BLOCK_DURATION_TOO_LONG: "errors.BLOCK_DURATION_TOO_LONG",
  BOOKING_NOT_FOUND: "errors.BOOKING_NOT_FOUND",
  CANCELLATION_REASON_REQUIRED: "errors.CANCELLATION_REASON_REQUIRED",
  CANNOT_DEMOTE_SELF: "errors.CANNOT_DEMOTE_SELF",
  CANNOT_RESTRICT_SELF: "errors.CANNOT_RESTRICT_SELF",
  CANNOT_REVOKE_SELF: "errors.CANNOT_REVOKE_SELF",
  CAPABILITY_RESTRICTED: "errors.CAPABILITY_RESTRICTED",
  CURRENT_PASSWORD_INCORRECT: "errors.CURRENT_PASSWORD_INCORRECT",
  DURATION: "errors.DURATION",
  EMAIL_CHANGE_SUPERSEDED: "errors.EMAIL_CHANGE_SUPERSEDED",
  EMAIL_DELIVERY_UNAVAILABLE: "errors.EMAIL_DELIVERY_UNAVAILABLE",
  EMAIL_TAKEN: "errors.EMAIL_TAKEN",
  EMAIL_UNCHANGED: "errors.EMAIL_UNCHANGED",
  EMAIL_VERIFICATION_REQUIRED: "errors.EMAIL_VERIFICATION_REQUIRED",
  EMPTY_RECURRENCE: "errors.EMPTY_RECURRENCE",
  EVENT_FULL: "errors.EVENT_FULL",
  INTERNAL_ERROR: "errors.INTERNAL_ERROR",
  INVALID_BLOCK_RANGE: "errors.INVALID_BLOCK_RANGE",
  INVALID_CREDENTIALS: "errors.INVALID_CREDENTIALS",
  INVALID_IMAGE: "errors.INVALID_IMAGE",
  INVALID_PARTICIPANT: "errors.INVALID_PARTICIPANT",
  INVALID_RANGE: "errors.INVALID_RANGE",
  INVALID_RECURRENCE_RANGE: "errors.INVALID_RECURRENCE_RANGE",
  INVALID_RESTRICTION_RANGE: "errors.INVALID_RESTRICTION_RANGE",
  INVALID_RESTRICTION_SCOPE: "errors.INVALID_RESTRICTION_SCOPE",
  INVALID_ROOM_IMAGE: "errors.INVALID_ROOM_IMAGE",
  INVALID_TIME: "errors.INVALID_TIME",
  INVALID_TIMEZONE: "errors.INVALID_TIMEZONE",
  INVALID_VERIFICATION_TOKEN: "errors.INVALID_VERIFICATION_TOKEN",
  INVALID_WORKING_DAYS: "errors.INVALID_WORKING_DAYS",
  INVALID_WORK_HOURS: "errors.INVALID_WORK_HOURS",
  INVITATION_NOT_FOUND: "errors.INVITATION_NOT_FOUND",
  LAST_ADMIN: "errors.LAST_ADMIN",
  NAME_REQUIRED: "errors.NAME_REQUIRED",
  NOT_BOOKING_OWNER: "errors.NOT_BOOKING_OWNER",
  OUTSIDE_WORKING_DAYS: "errors.OUTSIDE_WORKING_DAYS",
  OUTSIDE_WORKING_HOURS: "errors.OUTSIDE_WORKING_HOURS",
  PASSWORD_LENGTH: "errors.PASSWORD_LENGTH",
  PASSWORD_UNCHANGED: "errors.PASSWORD_UNCHANGED",
  PAST: "errors.PAST",
  RECURRENCE_END_REQUIRED: "errors.RECURRENCE_END_REQUIRED",
  RECURRENCE_WEEKDAYS_REQUIRED: "errors.RECURRENCE_WEEKDAYS_REQUIRED",
  RESTRICTION_NOT_FOUND: "errors.RESTRICTION_NOT_FOUND",
  ROOM_BLOCK_NOT_FOUND: "errors.ROOM_BLOCK_NOT_FOUND",
  ROOM_BLOCK_SERIES_NOT_FOUND: "errors.ROOM_BLOCK_SERIES_NOT_FOUND",
  ROOM_CAPACITY_EXCEEDED: "errors.ROOM_CAPACITY_EXCEEDED",
  ROOM_IMAGE_REQUIRED: "errors.ROOM_IMAGE_REQUIRED",
  ROOM_NOT_FOUND: "errors.ROOM_NOT_FOUND",
  ROOM_UNAVAILABLE: "errors.ROOM_UNAVAILABLE",
  SESSION_EXPIRED: "errors.SESSION_EXPIRED",
  SLOT_ALIGNMENT: "errors.SLOT_ALIGNMENT",
  SLOT_TAKEN: "errors.SLOT_TAKEN",
  TELEGRAM_NOT_CONFIGURED: "errors.TELEGRAM_NOT_CONFIGURED",
  TITLE_REQUIRED: "errors.TITLE_REQUIRED",
  TOO_MANY_OCCURRENCES: "errors.TOO_MANY_OCCURRENCES",
  UNAUTHENTICATED: "errors.UNAUTHENTICATED",
  USER_NOT_FOUND: "errors.USER_NOT_FOUND",
  VALIDATION_ERROR: "errors.VALIDATION_ERROR",
};

export function errorMessage(
  error: unknown,
  t: Translator,
  fallback: MessageKey = "errors.generic",
): string {
  if (error instanceof ApiError) {
    const key = apiErrorKeys[error.code];
    if (key) {
      if (error.code === "CAPABILITY_RESTRICTED") {
        const reason =
          typeof error.details === "object" &&
          error.details !== null &&
          "reason" in error.details
            ? String(error.details.reason)
            : "";
        return reason
          ? t("errors.CAPABILITY_RESTRICTED_REASON", { reason })
          : t(key);
      }
      return t(key);
    }
  }
  if (error instanceof TypeError) return t("errors.network");
  return t(fallback);
}
